### ISSUE TITLE
Sometimes it just doesn't work and uses the default folder

### ISSUE THREAD

**Issue by BluebirdYT** [enjarai/shared-resources#28]
This error appeared in my logs: "[Render thread/ERROR]: Failed to parse allowed_symlinks.txt, disallowing all symbolic links" which is my best guess to why it is happening.
This is the only thing that could probably help in my log file:

[12:50:36] [Render thread/ERROR]: Failed to parse allowed_symlinks.txt, disallowing all symbolic links
java.nio.file.AccessDeniedException: C:\Users\bluebird\AppData\Roaming\PrismLauncher\global\saves
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:380) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:432) ~[?:?]
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422) ~[?:?]
	at java.nio.file.Files.newInputStream(Files.java:160) ~[?:?]
	at java.nio.file.Files.newBufferedReader(Files.java:2922) ~[?:?]
	at java.nio.file.Files.newBufferedReader(Files.java:2955) ~[?:?]
	at net.minecraft.class_32.method_52235(class_32.java:128) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:525) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]

**Comment by bloodyeyesblackblood** [comment]
well kinda same for me, mostly for the shaderpacks folder, can't find anything in my logs.

**Comment by enjarai** [comment]
It seems like Minecraft doesn't have permission to read/write from and to the global directory you selected. You'll have to ensure these permissions are granted for the user you're logged in as from within windows, or choose another directory.
