### ISSUE TITLE
Shared shaders doesn't work

### ISSUE THREAD

**Issue by Felix14-v2** [enjarai/shared-resources#31]
### To reproduce:
1. Install Shared Resources
2. Install Iris
3. Set the resources folder and enable shared shaders
4. Restart the game
5. Iris can't find the shaders

### Additional
<details>
 <summary>latest.log</summary>

```
[10:38:51] [main/INFO]: Loading Minecraft 1.20.2 with Fabric Loader 0.14.24
[10:38:51] [main/INFO]: Loading 67 mods:
	- amecs 1.3.11+mc.1.20.2
	   \-- amecsapi 1.5.5+mc1.20.2
	- cloth-config 12.0.109
	   \-- cloth-basic-math 0.6.1
	- fabric-api 0.91.1+1.20.2
	   |-- fabric-api-base 0.4.33+fce67b32a0
	   |-- fabric-api-lookup-api-v1 1.6.42+b1792f7da0
	   |-- fabric-biome-api-v1 13.0.14+b1792f7da0
	   |-- fabric-block-api-v1 1.0.12+73761d2ea0
	   |-- fabric-block-view-api-v2 1.0.1+73761d2ea0
	   |-- fabric-blockrenderlayer-v1 1.1.43+f4b7e424a0
	   |-- fabric-client-tags-api-v1 1.1.4+86b12645a0
	   |-- fabric-command-api-v1 1.2.37+f71b366fa0
	   |-- fabric-command-api-v2 2.2.16+b1792f7da0
	   |-- fabric-commands-v0 0.2.54+df3654b3a0
	   |-- fabric-containers-v0 0.1.77+df3654b3a0
	   |-- fabric-content-registries-v0 5.0.5+b1792f7da0
	   |-- fabric-convention-tags-v1 1.5.8+b1792f7da0
	   |-- fabric-crash-report-info-v1 0.2.20+f4b7e424a0
	   |-- fabric-data-generation-api-v1 13.1.7+b1792f7da0
	   |-- fabric-dimensions-v1 2.1.57+b1792f7da0
	   |-- fabric-entity-events-v1 1.5.26+b1792f7da0
	   |-- fabric-events-interaction-v0 0.6.10+b1792f7da0
	   |-- fabric-events-lifecycle-v0 0.2.69+df3654b3a0
	   |-- fabric-game-rule-api-v1 1.0.42+a44e16a6a0
	   |-- fabric-item-api-v1 2.1.33+b1792f7da0
	   |-- fabric-item-group-api-v1 4.0.15+e3d2bf3fa0
	   |-- fabric-key-binding-api-v1 1.0.38+f4b7e424a0
	   |-- fabric-keybindings-v0 0.2.36+df3654b3a0
	   |-- fabric-lifecycle-events-v1 2.2.27+b1792f7da0
	   |-- fabric-loot-api-v2 2.1.1+3ba460fba0
	   |-- fabric-message-api-v1 6.0.2+e3d2bf3fa0
	   |-- fabric-mining-level-api-v1 2.1.55+f4b7e424a0
	   |-- fabric-model-loading-api-v1 1.0.6+b1792f7da0
	   |-- fabric-models-v0 0.4.5+9386d8a7a0
	   |-- fabric-networking-api-v1 3.1.1+e3b69503a0
	   |-- fabric-object-builder-api-v1 12.1.2+2ff98d3ba0
	   |-- fabric-particles-v1 1.1.4+f4b7e424a0
	   |-- fabric-recipe-api-v1 2.0.10+52b3ebe5a0
	   |-- fabric-registry-sync-v0 4.0.8+b1792f7da0
	   |-- fabric-renderer-api-v1 3.2.1+2034447ca0
	   |-- fabric-renderer-indigo 1.5.1+2034447ca0
	   |-- fabric-renderer-registries-v1 3.2.49+df3654b3a0
	   |-- fabric-rendering-data-attachment-v1 0.3.39+73761d2ea0
	   |-- fabric-rendering-fluids-v1 3.0.30+f4b7e424a0
	   |-- fabric-rendering-v0 1.1.52+df3654b3a0
	   |-- fabric-rendering-v1 3.0.11+b1792f7da0
	   |-- fabric-resource-conditions-api-v1 2.3.11+239dafd8a0
	   |-- fabric-resource-loader-v0 0.11.12+b1792f7da0
	   |-- fabric-screen-api-v1 2.0.12+b1792f7da0
	   |-- fabric-screen-handler-api-v1 1.3.43+b1792f7da0
	   |-- fabric-sound-api-v1 1.0.14+f4b7e424a0
	   |-- fabric-transfer-api-v1 3.3.11+9ab11d52a0
	   \-- fabric-transitive-access-wideners-v1 5.0.3+fce67b32a0
	- fabricloader 0.14.24
	- iris 1.6.10
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- java 17
	- minecraft 1.20.2
	- modmenu 8.0.0
	- shared-resources 1.7.0
	   |-- com_github_llamalad7_mixinextras 0.1.1
	   |-- shared-resources-api 1.7.0
	   \-- shared-resources-mc20-2 1.7.0
	- sodium 0.5.3
[10:38:51] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/%d0%94%d0%be%d0%bc%d0%b0%d1%88%d0%bd%d0%b8%d0%b9%20%d0%ba%d0%be%d0%bc%d0%bf%d1%8c%d1%8e%d1%82%d0%b5%d1%80/AppData/Roaming/.theseus/meta/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[10:38:51] [main/INFO]: Compatibility level set to JAVA_16
[10:38:51] [main/INFO]: Compatibility level set to JAVA_17
[10:38:52] [main/WARN]: Reference map 'shared-resources-api-refmap.json' for shared-resources-api.mixins.json could not be read. If this is a development environment you can ignore this message
[10:38:52] [main/INFO]: Loaded configuration file for Sodium: 41 options available, 3 override(s) found
[10:38:53] [main/WARN]: Error loading class: net/minecraft/client/util/ScreenshotUtils (java.lang.ClassNotFoundException: net/minecraft/client/util/ScreenshotUtils)
[10:38:53] [main/WARN]: @Mixin target net/minecraft/client/util/ScreenshotUtils was not found shared-resources.mixins.json:screenshots.ScreenshotUtilsMixin from mod shared-resources
[10:38:53] [main/INFO]: Instancing error handler class nl.enjarai.shared_resources.common.compat.CompatMixinErrorHandler
[10:38:53] [main/WARN]: Failed to apply mixin emotecraft.EmoteInstanceMixin for package emotecraft! Compatibility with the corresponding mod will most likely not work!
[10:38:53] [main/WARN]: Mixin prepare for mod shared-resources failed preparing emotecraft.EmoteInstanceMixin in shared-resources.compat.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException java.lang.NullPointerException: Cannot read the array length because "<local6>" is null
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: java.lang.NullPointerException: Cannot read the array length because "<local6>" is null
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:886) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.24.jar:?]
Caused by: java.lang.NullPointerException: Cannot read the array length because "<local6>" is null
	at nl.enjarai.shared_resources.common.compat.CompatMixinPlugin.shouldApplyMixin(CompatMixinPlugin.java:40) ~[shared-resources-1.7.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.shouldApplyMixin(PluginHandle.java:132) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.shouldApplyMixin(MixinInfo.java:988) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:953) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:882) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	... 22 more
[10:38:53] [main/WARN]: Force-disabling mixin 'features.render.entity.CuboidMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[10:38:53] [main/WARN]: Force-disabling mixin 'features.render.entity.ModelPartMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[10:38:53] [main/WARN]: Force-disabling mixin 'features.render.entity.cull.EntityRendererMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[10:38:53] [main/WARN]: Force-disabling mixin 'features.render.entity.shadows.EntityRenderDispatcherMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[10:38:53] [main/WARN]: Force-disabling mixin 'features.render.gui.font.GlyphRendererMixin' as rule 'mixin.features.render.gui.font' (added by mods [iris]) disables it and children
[10:38:53] [main/WARN]: Force-disabling mixin 'features.render.world.sky.BackgroundRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[10:38:53] [main/WARN]: Force-disabling mixin 'features.render.world.sky.ClientWorldMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[10:38:53] [main/WARN]: Force-disabling mixin 'features.render.world.sky.WorldRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[10:38:54] [main/INFO]: Mod iris is loaded, enabling compat.
[10:38:54] [main/INFO]: Searching for graphics cards...
[10:38:54] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=INTEL, name=Intel(R) UHD Graphics 630, version=DriverVersion=27.20.100.9664]
[10:38:54] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=NVIDIA, name=NVIDIA GeForce GTX 1050, version=DriverVersion=31.0.15.3758]
[10:38:54] [main/WARN]: Sodium has applied one or more workarounds to prevent crashes or other issues on your system: [NVIDIA_THREADED_OPTIMIZATIONS]
[10:38:54] [main/WARN]: This is not necessarily an issue, but it may result in certain features or optimizations being disabled. You can sometimes fix these issues by upgrading your graphics driver.
[10:39:01] [Datafixer Bootstrap/INFO]: 192 Datafixer optimizations took 336 milliseconds
[10:39:05] [Render thread/ERROR]: Failed to parse allowed_symlinks.txt, disallowing all symbolic links
java.nio.file.AccessDeniedException: C:\Users\Домашний компьютер\AppData\Roaming\.minecraft\home\Общий Minecraft\saves
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:380) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:432) ~[?:?]
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422) ~[?:?]
	at java.nio.file.Files.newInputStream(Files.java:160) ~[?:?]
	at java.nio.file.Files.newBufferedReader(Files.java:2922) ~[?:?]
	at java.nio.file.Files.newBufferedReader(Files.java:2955) ~[?:?]
	at net.minecraft.class_32.method_52235(class_32.java:135) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:438) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:214) ~[1.20.2-0.14.24.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.24.jar:?]
[10:39:05] [Render thread/INFO]: Environment: Environment[accountsHost=https://api.mojang.com, sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[10:39:06] [Render thread/INFO]: Setting user: Felix14_v2
[10:39:07] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[10:39:07] [Worker-Main-2/INFO]: Checking mod updates...
[10:39:07] [Render thread/INFO]: Unaccepted options.txt Key: "key_key.gamma_utils.night_vision_toggle" with value: "key.keyboard.unknown". Storing seperately to ensure it is not lost.
[10:39:07] [Render thread/INFO]: Unaccepted options.txt Key: "key_key.dynamic_fps.toggle_forced" with value: "key.keyboard.unknown". Storing seperately to ensure it is not lost.
[10:39:07] [Render thread/INFO]: Unaccepted options.txt Key: "key_zoomify.key.zoom" with value: "key.keyboard.c". Storing seperately to ensure it is not lost.
[10:39:07] [Render thread/INFO]: Unaccepted options.txt Key: "key_key.gamma_utils.min_gamma" with value: "key.keyboard.unknown". Storing seperately to ensure it is not lost.
[10:39:07] [Render thread/INFO]: Unaccepted options.txt Key: "key_key.gamma_utils.increase_gamma" with value: "key.keyboard.equal". Storing seperately to ensure it is not lost.
[10:39:07] [Render thread/INFO]: Unaccepted options.txt Key: "key_key.gamma_utils.max_gamma" with value: "key.keyboard.unknown". Storing seperately to ensure it is not lost.
[10:39:07] [Render thread/INFO]: Unaccepted options.txt Key: "key_zoomify.key.zoom.secondary" with value: "key.keyboard.unknown". Storing seperately to ensure it is not lost.
[10:39:07] [Render thread/INFO]: Unaccepted options.txt Key: "key_key.dynamic_fps.toggle_disabled" with value: "key.keyboard.unknown". Storing seperately to ensure it is not lost.
[10:39:07] [Render thread/INFO]: Unaccepted options.txt Key: "key_key.entityculling.toggle" with value: "key.keyboard.unknown". Storing seperately to ensure it is not lost.
[10:39:07] [Render thread/INFO]: Unaccepted options.txt Key: "key_key.gamma_utils.decrease_gamma" with value: "key.keyboard.minus". Storing seperately to ensure it is not lost.
[10:39:07] [Render thread/INFO]: Unaccepted options.txt Key: "key_key.gamma_utils.gamma_toggle" with value: "key.keyboard.backslash". Storing seperately to ensure it is not lost.
[10:39:07] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[10:39:08] [Render thread/WARN]: Attempting to apply workarounds for the NVIDIA Graphics Driver...
[10:39:08] [Render thread/WARN]: If the game crashes immediately after this point, please make a bug report: https://github.com/CaffeineMC/sodium-fabric/issues
[10:39:08] [Render thread/INFO]: ... Successfully applied workarounds for the NVIDIA Graphics Driver!
[10:39:08] [Worker-Main-2/INFO]: Update available for 'cloth-config@12.0.109', (-> 12.0.111+fabric)
[10:39:08] [Render thread/INFO]: OpenGL Vendor: NVIDIA Corporation
[10:39:08] [Render thread/INFO]: OpenGL Renderer: NVIDIA GeForce GTX 1050/PCIe/SSE2
[10:39:08] [Render thread/INFO]: OpenGL Version: 3.2.0 NVIDIA 537.58
[10:39:08] [ForkJoinPool.commonPool-worker-1/WARN]: [Iris Update Check] This version doesn't have an update index, skipping.
[10:39:08] [Render thread/INFO]: Debug functionality is disabled.
[10:39:08] [Render thread/INFO]: ARB_direct_state_access detected, enabling DSA.
[10:39:08] [Render thread/INFO]: Shaders are disabled because enableShaders is set to false in iris.properties
[10:39:08] [Render thread/INFO]: Shaders are disabled
[10:39:08] [Render thread/INFO]: Found non-pack entry 'C:\Users\Домашний компьютер\AppData\Roaming\.theseus\profiles\Fabric 1.20.2 для тестов\resourcepacks\folder.json', ignoring
[10:39:08] [Render thread/INFO]: Found non-pack entry 'C:\Users\Домашний компьютер\AppData\Roaming\.theseus\profiles\Fabric 1.20.2 для тестов\resourcepacks\folder.json.disabled', ignoring
[10:39:08] [Render thread/INFO]: Found non-pack entry 'C:\Users\Домашний компьютер\AppData\Roaming\.theseus\profiles\Fabric 1.20.2 для тестов\resourcepacks\resourcepacks.lnk', ignoring
[10:39:08] [Render thread/INFO]: Found non-pack entry 'C:\Users\Домашний компьютер\AppData\Roaming\.minecraft\home\Общий Minecraft\resourcepacks\1.15', ignoring
[10:39:08] [Render thread/INFO]: Found non-pack entry 'C:\Users\Домашний компьютер\AppData\Roaming\.minecraft\home\Общий Minecraft\resourcepacks\1.16', ignoring
[10:39:08] [Render thread/INFO]: Found non-pack entry 'C:\Users\Домашний компьютер\AppData\Roaming\.minecraft\home\Общий Minecraft\resourcepacks\1.16.5', ignoring
[10:39:09] [Render thread/INFO]: Found non-pack entry 'C:\Users\Домашний компьютер\AppData\Roaming\.minecraft\home\Общий Minecraft\resourcepacks\1.17.1', ignoring
[10:39:09] [Render thread/INFO]: Found non-pack entry 'C:\Users\Домашний компьютер\AppData\Roaming\.minecraft\home\Общий Minecraft\resourcepacks\1.18', ignoring
[10:39:09] [Render thread/INFO]: Found non-pack entry 'C:\Users\Домашний компьютер\AppData\Roaming\.minecraft\home\Общий Minecraft\resourcepacks\1.18.2', ignoring
[10:39:09] [Render thread/INFO]: Found non-pack entry 'C:\Users\Домашний компьютер\AppData\Roaming\.minecraft\home\Общий Minecraft\resourcepacks\1.19', ignoring
[10:39:09] [Render thread/WARN]: Missing metadata in pack file/Aquatic Wars III.zip
[10:39:09] [Render thread/INFO]: Found non-pack entry 'C:\Users\Домашний компьютер\AppData\Roaming\.minecraft\home\Общий Minecraft\resourcepacks\Dark Containers  (v0.5).zip.rpo', ignoring
[10:39:09] [Render thread/INFO]: Found non-pack entry 'C:\Users\Домашний компьютер\AppData\Roaming\.minecraft\home\Общий Minecraft\resourcepacks\Dark_Transparent_GUI_v3.0.zip.rpo', ignoring
[10:39:09] [Render thread/INFO]: Found non-pack entry 'C:\Users\Домашний компьютер\AppData\Roaming\.minecraft\home\Общий Minecraft\resourcepacks\Menus Enchanted 1.19.4.rpo', ignoring
[10:39:09] [Render thread/INFO]: Found non-pack entry 'C:\Users\Домашний компьютер\AppData\Roaming\.minecraft\home\Общий Minecraft\resourcepacks\Modrinth gui by bergusha and Felix14_v2.rpo', ignoring
[10:39:09] [Render thread/INFO]: Found non-pack entry 'C:\Users\Домашний компьютер\AppData\Roaming\.minecraft\home\Общий Minecraft\resourcepacks\shaped-like-egg-e141.zip.rpo', ignoring
[10:39:10] [Render thread/INFO]: Found non-pack entry 'C:\Users\Домашний компьютер\AppData\Roaming\.minecraft\home\Общий Minecraft\resourcepacks\TeslaCrystal.png', ignoring
[10:39:10] [Render thread/INFO]: Found non-pack entry 'C:\Users\Домашний компьютер\AppData\Roaming\.minecraft\home\Общий Minecraft\resourcepacks\Оф', ignoring
[10:39:11] [Render thread/INFO]: Hardware information:
[10:39:11] [Render thread/INFO]: CPU: 8x Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
[10:39:11] [Render thread/INFO]: GPU: NVIDIA GeForce GTX 1050/PCIe/SSE2 (Supports OpenGL 3.2.0 NVIDIA 537.58)
[10:39:11] [Render thread/INFO]: OS: Windows 11 (10.0)
[10:39:12] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric (amecs, amecsapi, cloth-config, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, iris, modmenu, shared-resources, shared-resources-api, shared-resources-mc20-2, sodium), file/Переводы всего, file/TeslaCraft 1.19.4
[10:39:12] [Render thread/WARN]: Non [a-z0-9_.-] character in namespace Архив.lnk in pack C:\Users\Домашний компьютер\AppData\Roaming\.minecraft\home\Общий Minecraft\resourcepacks\Переводы всего, ignoring
[10:39:12] [Render thread/WARN]: Non [a-z0-9_.-] character in namespace Архив.lnk in pack C:\Users\Домашний компьютер\AppData\Roaming\.minecraft\home\Общий Minecraft\resourcepacks\Переводы всего, ignoring
[10:39:12] [Worker-Main-2/INFO]: Found unifont_all_no_pua-15.0.06.hex, loading
[10:39:12] [Worker-Main-7/ERROR]: Invalid path in pack: minecraft:models/item/cases/hw21/cat_ears — копия.json, ignoring
[10:39:13] [Worker-Main-2/WARN]: Texture minecraft:item/cases/sc22/pticy/heart with size 8x8 limits mip level from 4 to 3
[10:39:13] [Worker-Main-2/WARN]: Texture minecraft:item/cases/sc22/pticy/bird_pet_eyes_texture with size 4x4 limits mip level from 3 to 2
[10:39:13] [Worker-Main-2/WARN]: minecraft:textures/atlas/blocks.png: dropping miplevel from 4 to 2, because of minimum power of two: 4
[10:39:14] [Worker-Main-4/WARN]: Unable to load model: 'minecraft:item/cases/hw21/halloween_key' referenced from: minecraft:golden_hoe#inventory: java.io.FileNotFoundException: minecraft:models/item/cases/hw21/halloween_key.json
[10:39:14] [Worker-Main-4/WARN]: Unable to load model: 'minecraft:item/cases/hw22/prizraki/cat_ghost_pet_not_animated' referenced from: minecraft:diamond_shovel#inventory: java.io.FileNotFoundException: minecraft:models/item/cases/hw22/prizraki/cat_ghost_pet_not_animated.json
[10:39:15] [Render thread/WARN]: Skipped language file: recursiveresources:lang/en_us.json (com.google.gson.JsonSyntaxException: Expected recursiveresources to be a string, was an object ({"so..."}}))
[10:39:15] [Render thread/WARN]: Skipped language file: recursiveresources:lang/ru_ru.json (com.google.gson.JsonSyntaxException: Expected recursiveresources to be a string, was an object ({"so..."}}))
[10:39:15] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[10:39:15] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[10:39:15] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Динамики (2- USB PnP Sound Device)
[10:39:15] [Render thread/INFO]: Sound engine started
[10:39:16] [Render thread/INFO]: Created: 2048x1024x2 minecraft:textures/atlas/blocks.png-atlas
[10:39:16] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[10:39:16] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[10:39:16] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[10:39:16] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[10:39:16] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[10:39:16] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[10:39:16] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[10:39:16] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[10:39:16] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[10:39:16] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[10:39:16] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[10:39:16] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[10:39:16] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/gui.png-atlas
[10:39:16] [Render thread/INFO]: Creating pipeline for dimension NamespacedId{namespace='minecraft', name='overworld'}
[10:39:21] [IO-Worker-1/ERROR]: Couldn't connect to realms
net.minecraft.class_4355: Realms service error (500) with message 'Не удалось подключиться к Realms: Connect timed out'
	at net.minecraft.class_4341.method_20998(class_4341.java:441) ~[client-intermediary.jar:?]
	at net.minecraft.class_4341.method_21027(class_4341.java:218) ~[client-intermediary.jar:?]
	at net.minecraft.class_8647.method_52627(class_8647.java:45) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:39:27] [Render thread/INFO]: Stopping!

```
</details>

[latest.log](https://github.com/enjarai/shared-resources/files/13484993/latest.log)

**Comment by enjarai** [comment]
Fixed in the latest version.
